# .github/workflows/docker-build.yml
name: Build and Push Docker Image to GHCR

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: git clone https://github.com/CMCS-Norway/fortigate_exporter.git

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: fortigate_exporter/go.mod
          cache-dependency-path: fortigate_exporter/go.sum

      - name: Build fortigate_exporter binary
        run: |
          cd fortigate_exporter
          make build
          # Copy the built binary to the expected location for Dockerfile
          mkdir -p .build/linux-amd64/
          cp fortigate_exporter .build/linux-amd64/

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=tag
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./fortigate_exporter
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
